import "./globals.css";
import AOSProvider from "@/components/AOSProvider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className="antialiased">
        <AOSProvider />
        {children}
        </body>
        </html>
    );
}
